//main
export const GET_DATA_START = 'GET_DATA_START';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const GET_NEXT_BOOK_INFO_SUCCESS = 'GET_NEXT_BOOK_INFO_SUCCESS';
export const MAX_PAGE_CHANGED = 'MAX_PAGE_CHANGED';
export const MIN_PAGE_CHANGED = 'MIN_PAGE_CHANGED';
export const APPLY_FILTER_CLICK = 'APPLY_FILTER_CLICK';
export const LANGUAGE_CHECKED_CHANGED = 'LANGUAGE_CHECKED_CHANGED';
export const AUTHOR_CHECKED_CHANGED = 'AUTHOR_CHECKED_CHANGED';
export const RESET_FILTER = 'RESET_FILTER';

//books
export const GET_BOOK_DETAILS_START = 'GET_BOOK_DETAILS_START';
export const GET_BOOK_DETAILS_SUCCESS = 'GET_BOOK_DETAILS_SUCCESS';
export const GET_BOOK_DETAILS_ERROR = 'GET_BOOK_DETAILS_ERROR';

export const BOOK_DELETE_START = 'BOOK_DELETE_START';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_ERROR = 'BOOK_DELETE_ERROR';

export const CREATE_BOOK_GET_START = 'CREATE_BOOK_GET_START';
export const CREATE_BOOK_GET_SUCCESS = 'CREATE_BOOK_GET_SUCCESS';
export const CREATE_BOOK_GET_ERROR = 'CREATE_BOOK_GET_ERROR';

export const EDIT_BOOK_GET_START = 'EDIT_BOOK_GET_START';
export const EDIT_BOOK_GET_SUCCESS = 'EDIT_BOOK_GET_SUCCESS';
export const EDIT_BOOK_GET_ERROR = 'EDIT_BOOK_GET_ERROR';

export const SAVE_BOOK_START = 'SAVE_BOOK_START';
export const SAVE_BOOK_SUCCESS = 'SAVE_BOOK_SUCCESS';
export const SAVE_BOOK_ERROR = 'SAVE_BOOK_ERROR';

export const BOOK_COMMON_INPUT_CHANGED = 'BOOK_COMMON_INPUT_CHANGED';
export const BOOK_EDIT_INPUT_CHANGED = 'BOOK_EDIT_INPUT_CHANGED';

//tags
export const GET_TAGS_START = 'GET_TAGS_START';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';
export const EDIT_TAG = 'EDIT_TAG';
export const CANCEL_EDIT_TAG = 'CANCEL_EDIT_TAG';
export const SAVE_NEW_TAG_START = 'SAVE_NEW_TAG_START';
export const SAVE_NEW_TAG_ERROR = 'SAVE_NEW_TAG_ERROR';
export const SAVE_NEW_TAG_SUCCESS = 'SAVE_NEW_TAG_SUCCESS';
export const SAVE_EDITED_TAG_START = 'SAVE_EDITED_TAG_START';
export const SAVE_EDITED_TAG_ERROR = 'SAVE_EDITED_TAG_ERROR';
export const SAVE_EDITED_TAG_SUCCESS = 'SAVE_EDITED_TAG_SUCCESS';
export const DELETE_TAG_ERROR = 'DELETE_TAG_ERROR';
export const TAG_INPUT_CHANGED = 'TAG_INPUT_CHANGED';

//authors
export const GET_AUTHORS_START = 'GET_AUTHORS_START';
export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const GET_AUTHORS_ERROR = 'GET_AUTHORS_ERROR';
export const EDIT_AUTHOR = 'EDIT_AUTHOR';
export const CANCEL_EDIT_AUTHOR = 'CANCEL_EDIT_AUTHOR';
export const SAVE_NEW_AUTHOR_START = 'SAVE_NEW_AUTHOR_START';
export const SAVE_NEW_AUTHOR_ERROR = 'SAVE_NEW_AUTHOR_ERROR';
export const SAVE_NEW_AUTHOR_SUCCESS = 'SAVE_NEW_AUTHOR_SUCCESS';
export const SAVE_EDITED_AUTHOR_START = 'SAVE_EDITED_AUTHOR_START';
export const SAVE_EDITED_AUTHOR_ERROR = 'SAVE_EDITED_AUTHOR_ERROR';
export const SAVE_EDITED_AUTHOR_SUCCESS = 'SAVE_EDITED_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_ERROR = 'DELETE_AUTHOR_ERROR';
export const AUTHOR_INPUT_CHANGED = 'AUTHOR_INPUT_CHANGED';