//main
export const GET_DATA_START = 'GET_DATA_START';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const GET_NEXT_BOOK_INFO_SUCCESS = 'GET_NEXT_BOOK_INFO_SUCCESS';
export const MAX_PAGE_CHANGED = 'MAX_PAGE_CHANGED';
export const MIN_PAGE_CHANGED = 'MIN_PAGE_CHANGED';
export const APPLY_FILTER_CLICK = 'APPLY_FILTER_CLICK';
export const LANGUAGE_CHECKED_CHANGE = 'LANGUAGE_CHECKED_CHANGE';
export const AUTHOR_CHECKED_CHANGE = 'AUTHOR_CHECKED_CHANGE';
export const RESET_FILTER = 'RESET_FILTER';

//book
export const GET_BOOK_DETAILS_START = 'GET_BOOK_DETAILS_START';
export const GET_BOOK_DETAILS_SUCCESS = 'GET_BOOK_DETAILS_SUCCESS';
export const GET_BOOK_DETAILS_ERROR = 'GET_BOOK_DETAILS_ERROR';

export const BOOK_DELETE_START = 'BOOK_DELETE_START';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_ERROR = 'BOOK_DELETE_ERROR';

export const CREATE_BOOK_GET_START = 'CREATE_BOOK_GET_START';
export const CREATE_BOOK_GET_SUCCESS = 'CREATE_BOOK_GET_SUCCESS';
export const CREATE_BOOK_GET_ERROR = 'CREATE_BOOK_GET_ERROR';

export const EDIT_BOOK_GET_START = 'EDIT_BOOK_GET_START';
export const EDIT_BOOK_GET_SUCCESS = 'EDIT_BOOK_GET_SUCCESS';
export const EDIT_BOOK_GET_ERROR = 'EDIT_BOOK_GET_ERROR';

export const SAVE_BOOK_START = 'SAVE_BOOK_START';
export const SAVE_BOOK_SUCCESS = 'SAVE_BOOK_SUCCESS';
export const SAVE_BOOK_ERROR = 'SAVE_BOOK_ERROR';

export const BOOK_COMMON_INPUT_CHANGED = 'BOOK_COMMON_INPUT_CHANGED';
export const BOOK_EDIT_INPUT_CHANGED = 'BOOK_EDIT_INPUT_CHANGED';